### ISSUE TITLE
Spending.Location

### ISSUE THREAD

**Issue by dendi239** [romasku/money-log-docs#2]
I'd like to suggest storing the location of a transaction inside its model. It may be handy to use that information combined with other factors to identify the exact place where money was spent (e.g. using forthsquare API), or even build a map of money spending (at least using it in filters, like `at the city centre`, or `in Kharkiv`).

**Comment by romasku** [comment]
Good idea!

Though it can not be a required field, as for me. Some spending has to the selected place (like tickets for the airplane to USA borough online). Also, when users are entering spending, they can be just too lazy to add it.

Related point - "Location" type should be also available for custom fields.

**Comment by dendi239** [comment]
> Related point - "Location" type should be also available for custom fields.

I feel like it's a great idea, but can you suggest any example of using it? I can suggest only pickup/destination points for taxi spendings.
