### ISSUE TITLE
Filter/group grammar

### ISSUE THREAD

**Issue by dendi239** [romasku/money-log-docs#3]
I'd like to start a discussion about grammar for filter and group expression with this issue.

[Current design](https://github.com/romasku/money-log-docs/blob/main/entities.md#fields-3) specifies something like following:
* `<field_name>`, or `custom.<field_name>` (let's use `<field>` instead for further) for grouping
* `<expr1> and <expr2> and ... and <exprN>`, where `expr` has form `<field> <op> <constant>`
  * `<op>` is one of comparison operators taken from `<=>` (`<`, `<=`, `>`, `>=`, `==`, `!=`)
  * `<constant>` is either
    * literal (string, or number) — may be handy for numeric, string or categorian fields
    * relative date like `30d` (sounds like date range, hence it must be shorthand for `now.date - 30d`)
    * some special values like `this week`, `this month`, `this year`

I wanna remind important points that were mentioned earlier:
* `(<expr1>, <expr2>, ..., <exprN>)` handy for group index
* It may be convenient to use other operators as well, such as `date in last week`
* It may be convenient to use boolean functions on filters `(<expr1> && <expr2>) || expr3`
* One can say that `and`, `or` are better than `&&`, `||`
* If you take `and`, `or`, you may need to include `xor`, `not` as well

It seems to me like building grammar where every expression can be built out of other expressions like a good idea, but it appears to me like we need some small type system with at least: `time`, `date`, `timedelta`, `number`, `bool`

**Comment by romasku** [comment]
Let's introduce the _bultin function_ concept. I the syntax will be `function_name(arg1, arg2, ...)`. I suggest following functions:
- `today()` just returns today's date.
- `week(date)` converts date to "week" object.
- `month(date_or_week)` converts date or week to "month" object.
- `year(date_or_week_or_month)` converts to "year" object.
- `days(num)` create days delta with `num` days.
- `weeks(num)` create weeks delta with `num` weeks.
- `months(num)` create month delta with `num` months.
- `years(num)` create years delta with `num` years.

This way we will allow the following expressions:

Is this week:
```
week(date) == week(today())
```

Is last week:
```
week(date) == week(today()) - weeks(1)
```

This will also easily allow to group by weeks by just using `week(date)` as grouping expression.

**Comment by romasku** [comment]
I feel like the GitHub issue is not the best way to discuss some topic with a lot of unrelated parts. If you don't mind, I'll create public google docs with a design doc for grammar soon.

**Comment by dendi239** [comment]
> I feel like the GitHub issue is not the best way to discuss some topic with a lot of unrelated parts. If you don't mind, I'll create public google docs with a design doc for grammar soon.

Well, I don't like google docs either, but we can move to GitHub Discussions (you may need to turn this feature on) to discuss it. However, I felt like PR with grammar update may be a great way to close this issue

**Comment by dendi239** [comment]
> Let's introduce the bultin function concept. I the syntax will be function_name(arg1, arg2, ...). I suggest following functions:
> 
> - `today()` just returns today's date.
> - `week(date)` converts date to "week" object.
> - `month(date_or_week)` converts date or week to "month" object.
> - `year(date_or_week_or_month)` converts to "year" object.
> - `days(num)` create days delta with num days.
> - `weeks(num)` create weeks delta with num weeks.
> - `months(num)` create month delta with num months.
> - `years(num)` create years delta with num years.

I do like the builtins concept you suggested, however previous concept like `1y3m3w7d` seemed more convenient than `years(1) + months(3) + weeks(3) + days(7)`.

**Comment by romasku** [comment]
I am not sure about the idea of mixing different periods. The month has no fixed duration, and it's not clear what the following expressions should mean:
`date - today() == month(1)` (are "day of month" values are the same? are difference is 30 days?)
`month(data) - month(today()) == week(1)` (???)

So I suggest treating "days", "weeks", "month" and "years" as separate concepts that cannot be added/subtracted.

**Comment by dendi239** [comment]
Yeah, but there's no great way to build arifmetics on dates, e.g. `now() + 1w + 1m` may differ from `now() + 1m + 1w` if now is 25feb, for example.

**Comment by dendi239** [comment]
> So I suggest treating "days", "weeks", "month" and "years" as separate concepts that cannot be added/subtracted.

I do agree with it, and suggest treating notation `<expr> == 2m3d` as `month(<expr>) == 2 and days(<expr>) == 3`. Moreover, I don't see convenient way to perform any arifmetics between `date` and `timedelta` since `now() + 1w + 1m != now() + 1m + 1w`. 

There're two options I can suggest here:
* Treat `1m = 30d`, `1w = 7d`, `1y = 365d` and deal with it. 
  * pros:
    * easy to understand
    * easy to implement
    * allow to use more rich statements
   * cons:
     * `month(date) + 1` may differ from `month(date + 1m)`
     * hard to represent same day, but in other month/year
* Try to save year, month, week and day by limiting operations available:
  * `timedelta` can be compared with other `timedelta`, or added to `date`
  * Comparison between `timedelta`s equivalent to comparison between their components independently
  * Adding (substracting) `timedelta` to (from) `date` will try to change every component of `date` from top (`year`) to bottom with necessary corrections, if needed (e.g. if you substract `3m` from `25feb2020`, you will end up in `date` with a difference `1y-9m` which can be unexpected: note that `1y-9m != 3m`).

As you can see, there're a lot of problems with both approaches. There's an easy solution (at least for the first time): use library's behaviour to `time`, `date` and `timedelta` objects. If we stick with flutter, here's [their decision](https://api.flutter.dev/flutter/dart-core/DateTime-class.html) about it.

Bonus! There's a [funny video](https://youtu.be/-5wpm-gesOY) about converting time, so this topic may be (and is) a very huge, maybe we don't need to spend a lot of time to specifying `time`, `date` and `timedelta` behavior for now.

What do you think?

**Comment by romasku** [comment]
Sorry, I did not explain well what I meant:

My idea is to have separate "deltas" for different periods. In more detail:
- There are `Day`, `Week`, `Month`, `Year` types that represent some fixed duration of the real world. I mean that `Month` is not just a number from 1 to 12, it is a specific month in some specific year. Functions `week()`, `month()` and year()` just select a larger duration that fully contains argument. This means that `month()` and `year()` are not supported for `Week` (though it is meaningless so shouldn't be required). 
- To backward translation, we can define `first_day()` function with obvious functionality.
- There are `DayDelta`, `WeekDelta`, `MonthDelta` and `YearDelta` types that represent difference of the corresponding durations. For example, when you subtract `Week` from `Week` you get `WeekDelta`. Deltas of different types cannot be added or even transformed into each other like durations (probably we can allow `week(1) == days(7)`, but I do not think that is useful enough to break the rule). Deltas can be only added/subtracted to the corresponding duration.

This may sound uncommon for the programming world, but I think it is much closer how people think. This allows the definition of concepts like "previous week" (`week(today) - weeks(1)`) without any unexpected behaviors.

**Comment by romasku** [comment]
> Bonus! There's a funny video about converting time, so this topic may be (and is) a very huge, maybe we don't need to spend a lot of time to specifying time, date and timedelta behavior for now.

Solid point, but as it is a hobby project, I want to do what I am passionate about:). And at the moment, I like the challenge of this "date and timedelta" stuff. Also, I like (as a programmer) the idea of introducing micro language - it's always fun to make own compiler:)

**Comment by dendi239** [comment]
There's an elephant in the room we weren't talking about. I'd like to use a single structure `datetime` for representing date and time (fixed point of time) to minimize the amount of used types (say it to `<smth>delta`).

I do like idea of _just select a larger duration that fully contains argument_, but I must point out that `year(date_or_week_or_month)` and `month(date_or_week)` is not entirely correct, because the week isn't necessary either fits into, or disjoint to both of month and year.

I'd like to point out that `last week` now sounds like `week(.date) == week(today) - weeks(1)`, which kinda annoying. Let's bring some JS into it and use `1w` literal and strict conventions: `datetime` could implicitly converts to `<smth>`, but not vice versa, that way we could use: `.date == now - 1w` (not that clear, I know), but what if we use operator `in :: datetime, <smth>delta -> bool`: `.date in now - 1w`.

What do you think about implicit conversions and `operator in`?

**Comment by romasku** [comment]
As I wrote:

> This means that month() and year() are not supported for Week (though it is meaningless so shouldn't be required).

I think there is no need to convert week to `Month` and `Year` as it has no defined meaning.

**Comment by romasku** [comment]
About conversions:
If I got it correctly, you suggest casting both operands of bin operator expressions to "larger" (in means of duration type). For example `Day` and `Month` operands will be cast to `Month`, and `Month` and `Year` to `Year. This can be confusing:
- `now - 1d == now - 1y` checks "is today is the January 1" and can be `true`, through on first look it should never be `true` (we subtract different amounts from same value)
- `.date == now + 0w` checks "today is not the end of the week" and can be `false`, through on first look it should change nothing. We can overcome this by forbidding to use `0`, but I am not sure we will be always check for it in compile type (`week(today) - week(.date)` can be `0w`)

So though I do like the concise syntax (and I even wanted to agree at first), unfortunately, it can create strange expressions. And as such expressions will at most 1-3 lines long, it is probably to prefer correctness here.

About literals:
I like them, thanks! Let's use them.

About `in` operator: 
Also agree with your point here. The will also partially solve the casting problem:
`.date in week(today) - 1w`

**Comment by dendi239** [comment]
> you suggest casting both operands of bin operator expressions to "larger" (in means of duration type).

Not quite. I suggest implicit conversion **only from `datetime`** to `<smth>` (where `<smth>` is one of `second`, `minute`, `hour`, `day`, `week`, `month`, `year`), therefore:
* `now - 1d == now - 1y` is `CE`: comparison between `day` and `year`
* `.date == now + 0w` checks if `.date` and `now` are from same week

> it can create strange expressions

Can you show one (after my correction), please?

**Comment by dendi239** [comment]
Though, I wanna introduce "larger" hierarchy:
```
                               month - year
                             /
second - minute - hour - day 
                             \
                               week
```

**Comment by romasku** [comment]
I think that `seconds` and `minute` for manually entered spending is overkill - users never track the exact minute they entered something. And having only an `hour` is strange. Also, working with "time" automatically adds a complexity of timezone/DST/magic like "leap seconds". So I would like to keep working with dates only -- it just simpler. Also having both `minute` and `month` breaks literals (`1m`). We will have to introduce `1M`, and it will look inconsistent with other literals. I agree that it is solvable (`1s` `1m` `1h` `1D` `1W` `1M` `1Y`), but still.

About implicit conversions:
OK, got your idea.
What delta type should return `<datetime> - <datetime>`? If it is SecondsDelta (or DayDelta), then we lose commutativity:
`0w + today - today` - OK
`today - today + 0w` - CE
Also check the following:
`today + 1w` - OK
`(today - today + today) + 1w` - CE (it hurts from math perspective)
It will also require casts in some places:
It was a different month week ago `month(today - 7d) != today`. Note that there is only one cast, and it looks like we comparing month with day, which is strange. With `in` can be replaced with `today in month(today - 7d)` (no implicit casts).

That said, it looks like (for me) that implicit conversion will not give us that match (they do not cover all cases and cast can be easily added) but will make a general concept less "strict".

**Comment by dendi239** [comment]
> With in can be replaced with today in month(today - 7d) (no implicit casts).

Actually, idea of implicit casts was to use `today - 7d` instead of `day(today) - days(7)`.

**Comment by romasku** [comment]
> However, we can define type timedelta as a result <datetime> - <datetime> that can implicitly converts into <smth>Delta.

I thought about it, but it will not work: if delta is `3d` (or event `13s` if we support time), there is no way to upcast it to <smth>Delta that is larger.

> Actually, idea of implicit casts was to use today - 7d instead of day(today) - days(7)

If we make `today` a `day`, then it will be just correct without any casts :)

**Comment by romasku** [comment]
Difference between `today` and `.date` is more or less important:
`today - .date <= 10d`

**Comment by dendi239** [comment]
> Difference between `today` and `.date` is more or less important, as for me:
> `today - .date <= 10d`

Totally agree. It makes sense for adding comparison operators between `<smth>Delta` as well. However, it worth saying that `today - .date <= 1w` isn't the same as `today - .date <= 7d`.

**Comment by dendi239** [comment]
> I thought about it, but it will not work: if delta is 3d (or event 13s if we support time), there is no way to upcast it to Delta that is larger.

I don't like casting between different `<smth>Delta`s, but I wanna allow casting from generic `timedelta` to any of `<smth>Delta`, but only this way: to keep expressions like `today - .date == 3m`, `today - .date == 1y` and so on. Note that simple implementation may actually store two `datetime`s and calculate actually difference on casting.

**Comment by romasku** [comment]
It's not clear to me what `today - .date == 1y` means. Will be be true if `today` is 1 January 2021, and `.date` is 31 December 2020? And `today - .date == 1w` is even less clear here.

**Comment by dendi239** [comment]
> Will be be true if today is 1 January 2021, and .date is 31 December 2020

Yes. Because it's shorthand for `years(today) - years(.date) == 1y`.

> And today - .date == 1w is even less clear here.

Didn't get it, could you elaborate more, please?

**Comment by romasku** [comment]
I think it can be unexpected behavior that can lead to mistakes. If you want to check that some date was a week ago, your first thought (if you are not very familiar with lang) is to write `today - .date == 1w` and it will produce wrong result.
